# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: hello

on:
  pull_request:
    types: [opened]

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false
      review:
        description: Review ID
        required: false

jobs:
  prepare-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup git config
        run: |
          git config user.name 'CPLLou'
          git config user.email 'louis.gietzen@cloudpilots.com'
      - name: PR for Blog Post Updates
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr merge --auto --delete-branch "acceptance"

            # Set Variables depending on branch

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo Hello
        run: |
          echo "Hello World"

  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.TOKEN }}
          merge-method: rebase
          # do-not-merge-labels: never-merge
          # required-labels: automerge
          # pull-request: ${{ github.event.inputs.pull-request }}
          # review: ${{ github.event.inputs.review }}
          # dry-run: true
