# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: hello

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

            # Set Variables depending on branch
      - name: Echo Hello
        run: |
          echo "Hello World"      
      - name: Setup git config
        run: |
          git config user.name 'CPLLou'
          git config user.email 'louis.gietzen@cloudpilots.com'
      - name: PR for Blog Post Updates
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr merge --auto --delete-branch "acceptance"
